# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangens():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changens(self):
      self.driver.get("https://regweb.ics.forth.gr/hostmaster/signin.html")
      self.driver.set_window_size(1920, 1049)
      self.driver.find_element(By.NAME, "username").send_keys(os.environ["REGWEB_USERNAME"])
      self.driver.find_element(By.NAME, "password").send_keys(os.environ["REGWEB_PASSWORD"])
      self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()

      with open("./cloudflare_domains.csv", 'r') as f:
        domainsline = [line.strip() for line in f if line.strip() and not line.startswith('#')]
      # the file is a csv that has 
      # domain,status,ns1,ns2,all_nameservers
      # parts-service.gr,existing,mira.ns.cloudflare.com,rocky.ns.cloudflare.com,"mira.ns.cloudflare.com, rocky.ns.cloudflare.com"
      for line in domainsline:
        domain = line.split(',')[0]
        ns1 = line.split(',')[2]
        ns2 = line.split(',')[3]
        try:
          self.driver.get("https://regweb.ics.forth.gr/hostmaster/epp/update/domain.html?menuId=s21")
          self.driver.find_element(By.ID, "domainNameForInfo").send_keys(domain)
          self.driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
          time.sleep(2)
          self.driver.find_element(By.CSS_SELECTOR, "#deleteNameServersDelButton0 > .fa").click()
          time.sleep(0.2)
          self.driver.find_element(By.CSS_SELECTOR, "#deleteNameServersDelButton1 > .fa").click()
          time.sleep(0.2)
          if self.driver.find_elements(By.CSS_SELECTOR, "#deleteNameServersDelButton2 > .fa"):
            self.driver.find_element(By.CSS_SELECTOR, "#deleteNameServersDelButton2 > .fa").click()
          self.driver.find_element(By.NAME, "addNameServers[0]").click()
          self.driver.find_element(By.NAME, "addNameServers[0]").send_keys(ns1)
          time.sleep(0.2)
          self.driver.find_element(By.CSS_SELECTOR, "#addNameServers_AddButton > .fa-stack").click()
          time.sleep(0.2)
          self.driver.find_element(By.NAME, "addNameServers[1]").click()
          self.driver.find_element(By.NAME, "addNameServers[1]").send_keys(ns2)
          time.sleep(1)
          self.driver.find_element(By.NAME, "domainUpdate").click()
        except:
          pass
def main():
  test_changens = TestChangens()
  test_changens.setup_method(test_changens.test_changens)
  test_changens.test_changens()
  test_changens.teardown_method(test_changens.test_changens)

if __name__ == "__main__":
    main()